library(knitr)
library(rvest)
library(gsubfn)
library(tidyr)
library(tmap)
library(shiny)
library(dplyr)
library(readr)
library(readxl)
library(stringr)
library(ggpubr)
library(rgdal)
library(markdown)
library(DT)
library(rgeos)
library(digest)
library(ggplot2)
library(mosaic)
library(maptools)
library(extrafont)
library(tmap)
library(scales)
library(plyr)

options(gsubfn.engine="R")

# Uvozimo funkcije za pobiranje in uvoz zemljevida.
source("lib/uvozi.zemljevid.r", encoding="UTF-8")
